-- RETIRED: Do not use this file to initialize a database.
-- The authoritative fresh-install baseline is supabase/schema.sql.
-- Apply supabase/migrations/*.sql in filename order after the baseline.
-- Existing databases must receive only unapplied migrations; never rerun the baseline.
