ALTER TABLE public.alumni_allowlist ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.alumni_allowlist FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.alumni_allowlist TO service_role;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.members FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.members TO service_role;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.events FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.events TO service_role;
ALTER TABLE public.event_attendees ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.event_attendees FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_attendees TO service_role;
ALTER TABLE public.proposed_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.proposed_events FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.proposed_events TO service_role;
ALTER TABLE public.offerings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.offerings FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.offerings TO service_role;
ALTER TABLE public.forum_posts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.forum_posts FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_posts TO service_role;
ALTER TABLE public.forum_replies ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.forum_replies FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_replies TO service_role;
ALTER TABLE public.forum_memberships ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.forum_memberships FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_memberships TO service_role;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.admins FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.admins TO service_role;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.audit_log FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_log TO service_role;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.site_settings FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.site_settings TO service_role;
ALTER TABLE public.forum_memberships ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();
UPDATE public.forum_memberships SET created_at = joined_at WHERE joined_at IS NOT NULL;
